title: Test Pages
timezone: Europe/Zurich

markdown: kramdown
highlighter: rouge
syntax_highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
